version: "3.7"
services:
  app:
    build:
      args:
        user: adilimudassir
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: inertia-starter
    container_name: inertia-starter-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - inertia-starter

  db:
    image: mysql:8.0
    container_name: inertia-starter-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - inertia-starter

  nginx:
    image: nginx:alpine
    container_name: inertia-starter-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - inertia-starter

  redis:
    image: redis
    container_name: inertia-starter-redis
    volumes:
      ## keep redis data on localhost so we don't lose them ##
      - ./docker-volumes-data/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    networks: 
      - inertia-starter

networks:
  inertia-starter:
    driver: bridge